config/routes.rb
Rails.application.routes.draw do

	resources :photos,:path_names=>{:new=>:upload}
  devise_for :users,
						 :path => "user",
						 :controllers => {
		      		:registrations => "users/registrations",
					    :passwords     => "users/passwords",
							:sessions      => "users/sessions"
	    				},
						:path_names => {
							:sign_up => 'signup',
							:sign_in =>'login',
							:sign_out =>'logout'
						}

 root 'welcomes#index'
 get ':username'           => 'users#show',  :as=>:user_home
 get ":username/recent"          =>"users#recent",  :as=>"recent_users"
 
 get 'settings/edit'      =>'users#edit', :as=>"edit_settings"
 patch 'settings/edit'    =>'users#update'
 
 get 'settings/email'    =>"users#email",      :as=> "email_settings"

 resources :users, only: [:password , :profile] ,:path=>"settings" do
	 collection do
	 	get :password 
	 	patch :password
		get :profile 
		patch :profile
		get :social
		patch :social
	 end
 end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	mount_uploader :image,ImageUploader
	belongs_to :user

	def next
		Photo.where("id>?",id).first
	end
	def prev
		Photo.where("id<?",id).last
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	mount_uploader :avatar,AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :username, uniqueness: {case_sensitive: false},presence: true,format: { with: /\A[a-z0-9][a-z0-9-]*\z/i }
	has_many :photos, :dependent=>:destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	helper_method :resource, :resource_info, :devise_mapping

	def resource_info
		:user
	end

	def resource
		@resource ||= User.new
	end
	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	layout 'photo_show',only: :show
	before_action :authenticate_user!, :only=>[:new,:create,:destroy,:update,:edit]

  def index
		@photos = Photo.all.reverse
  end

	def new
		@photo = Photo.new 
	end

	def edit
    @db_photo=Photo.find(params[:id])
    if @db_photo.user == current_user
		  @photo = @db_photo
    else
      redirect_to photos_path
    end
	end

  def create
		@photo = current_user.photos.create photo_params	
		@user = current_user.username
		if @photo.save
			redirect_to user_home_path(@user)
		else
			render 'upload'
		end
  end

	def show
		@photos = Photo.all
		 @photo = Photo.find(params[:id])
	end

  def destroy
    @photo = Photo.find(params[:id])
		if @photo.destroy
			redirect_to user_home_path(current_user.username)
		end

  end
  def update
		@photo = current_user.photos.find(params[:id])
		p @photo
		if request.patch?
			if @photo.update params.require(:photo).permit(:title,:description)
				redirect_to recent_users_path(current_user.username)
			else
				render 'show'
			end
		end
  end

	private
	def photo_params
		params.require(:photo).permit(:image)
	end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	before_action :configure_permitted_parameters, only: [:create]

	protected

		def configure_permitted_parameters
			devise_parameter_sanitizer.for(:sign_up){|u| u.permit(:username, :email, :password)}
		end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, :only=>[:edit,:update,:password,:profile,:email,:social]

	def show
    @user = User.find_by_username(params[:username])
		@photos = @user.photos.reverse	
	end

	def edit
	end

	def recent
    @user = User.find_by_username(params[:username])
		@photos = @user.photos.last(8).reverse
	end

	def password
		if request.patch?
			if current_user.valid_password?(params[:user][:old_password]) and  current_user.update_attributes user_params
				redirect_to root_path
			else
				render 'password'
			end
		end
	end

	def email
	end
	
	def profile
		if request.patch?
			if current_user.update_attributes user_params
																								
				redirect_to profile_users_path
			else
				render 'profile'
			end
		end
	end

	def social
		if request.patch?
			if current_user.update_attributes user_params
				redirect_to social_users_path
			else
				render 'social'	
			end
		end
	end

	def update
		if current_user.update_attributes user_params
			redirect_to edit_settings_path
		else
			render 'edit'
		end
		
	end

	private

		def user_params
			params.require(:user).permit(:name, :username,
																	 :email,:password, 
																	 :avatar, :city,
																	 :sex, :website,
																	 :title, :bio,
																	 :qq, :weixin,
																	 :twitter, :facebook,
																	 :github)
		end
	
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picshare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body >
	<%= yield :head %>
	<%= yield :login%>
	<%= render "shared/header"=%>
	<%= yield %>
	<%= render "shared/footer"%>

</body>
</html>

app/views/layouts/photo_show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picshare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="photoshowbody" >
	<%= yield %>
</body>
</html>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/delete.html.erb
<h1>Photos#delete</h1>
<p>Find me in app/views/photos/delete.html.erb</p>

app/views/photos/edit.html.erb
<div class = " photo-edit  container">
	<div class="row">
		<div class="col-lg-9">
			<div class="edit-image">
				<%= image_tag @photo.image.url%>
			</div>
		</div>
		<div class="col-lg-3">
		<%= form_for @photo do |f|%>
			<div class="ui form  segment">
				<div class="field">
					<label>姓名</label>
					<%= f.text_field :title%>
				</div>
				<div class="field">
					<label>城市</label>
					<%= f.text_field :tag%>
				</div>
				<div class="field">
					<label>性别</label>
					<div class="ui selection dropdown">
						<%= f.hidden_field :catigory_id %>
						<div class="default text">性别</div>
							<i class="dropdown icon"></i>
						<div class="menu ui transition hidden">
							<div class="item" data-value="male"><i class="male icon"></i>男性</div>
							<div class="item" data-value="female"><i class="female icon"></i>女性</div>
						</div>
					</div>
				</div>
				<div class="field">
					<label>个人主页</label>
					<%= f.text_field :is_public%>
				</div>
				<label>个人简介</label>
				<%= f.text_area :description,:as=>:textarea%>


			</div>
		</div>
	<%end%>
	</div>
	
</div>

app/views/photos/index.html.erb
<div class="container" style="padding:0">
	<div class="gallery">
		<%@photos.each do |photo|%>
			<%= link_to image_tag(photo.image.medium.url),photo_path(photo),"data-target"=>"#photoModal","data-toggle"=>"modal",:class=>"preview each photo grid"%>
		<%end%>
	</div>
	
</div>
<div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="photo-modal">
		<div class="modal-dialog">
			
		</div>
	</div>
</div>

app/views/photos/new.html.erb
<div class="container" id ="photo_uploadarea">
	<div class="row">
		<div class="photo_upload">
			<%= form_for @photo ,:html => {:multipart => true} do |f|%>
			<span class="ui green massive button fileinput-button" id="fileinput-button">
				<i class="icon plus"></i><span>从您的电脑中选择照片</span>
				<%=f.file_field :image%>
			</span>
			<button type="submit" class="ui button">开始上传</button>
			<%end%>
		</div>
	</div>
</div>

app/views/photos/shared/_photo_display.html.erb
<div class=" photo_detail">
	<% @photos.each do |photo|%>
	<div class="each_photo">
		<div class="ui items">
			<div class="item">
				<div class="image">
					<%=link_to image_tag(photo.image.thumb.url),photo_path(photo),"data-target"=>"#photoModal",:class=>"preview","data-toggle"=>"modal" %>
					<%#<%=link_to image_tag(photo.image.thumb.url),photo.image.large.url,"data-lightbox"=>"image"  , :class=>"preview" %>
			   	<div class="ui simple  dropdown item corner label">
					 	<i class="edit icon"></i>
					 	<div class="menu">
							<%= link_to "编辑照片","##{photo.id}","data-target"=>"##{photo.id}",:class=>"item","data-toggle"=>"modal"%>
						 <%= link_to "删除照片",photo_path(photo),:method=> :delete,:class=>"item","data-confirm" => "确认永久删除此照片?"%>
					 	
					 	</div>
					</div>
					<div class="extra">
						<div class="caption">
							<%= photo.title %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal fade editphotomodal" id="<%=photo.id%>" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true">
	<div class="modal-page editphotomodal">
		<div class="modal-content">
			<div class="modal-header">
				<button  class="close" type="submit" data-dismiss="modal" aria-hidden="true">× </button>
				<h3>编辑照片信息</h3>
			</div>
			<div class="modal-body">
				<div class="ui form ">
					<%= form_for photo, :url=> photo_path(photo),method: :patch  do |f| %>
					<div class="field">
	  				<label >标题</label>
						<div class="ui labeled input">	
							<%= f.text_field :title,:placeholder=>"在这里输入照片的标题", autofocus: true %>
						</div>
					</div>
					<div class="field">
			  		<label >描述</label>
						<div class="ui labeled input">
							<%= f.text_area :description, :placeholder=>"在这里输入你的对照片的描述",autocomplete: "off" %>
						</div>
					</div>
					<button type="submit" class="ui button blue " >保存</button>
					<button  class="ui button left " data-dismiss="modal" style="float:right">取消</button>
					<% end %>
				</div>
			</div>
			
		</div>
	</div>
</div>
	<%end%>
</div>
<div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true">
	<div class="photo-modal">
		<div class="modal-dialog">
			
		</div>
	</div>
</div>

app/views/photos/show.html.erb
			<div class="pswrapper container" >
				<div class="row">
					<div class="large-image col-lg-9 ">
						<%=image_tag @photo.image.large.url%>
						<div class="changephoto">
							<% unless @photo.next.blank?%>
								<%=link_to '', photo_path(@photo.next),:class=>"icon-prev"%>
							<%end%>
							<% unless @photo.prev.blank?%>
								<%=link_to '' ,photo_path(@photo.prev),:class=>"icon-next"%>
							<%end%>
						</div>
					</div>
					<div class="image-info col-lg-3">
						<div class="modal-header">
							<div class="uploaderhead">
								<%=image_tag @photo.user.avatar.smallist.url, :class=>"avatar"%>
							</div>
							<div class="photouploadername">
								<%=link_to @photo.user.name,user_home_path(@photo.user), :class=>"name"%>
								<%= @photo.title%>
							<% if @photo.next.blank?%>
								<%=link_to '已经是第一张' ,''%>
						<%end%>
							<% if @photo.prev.blank?%>
								<%=link_to '已经是最后一张' ,''%>
						<%end%>
							</div>
							<div class="uploadertime">
								<p>上传时间：<%= @photo.created_at.strftime("%Y年%m月%d日")%></p>
								
							</div>
							<div class="isedit">
								<% if @photo.created_at == @photo.updated_at%>
									<p>未编辑</p>
								<% else %>
									<p>已编辑</p>
								<%end%>
							</div>
						</div>
						<div class="modal-body">
							<div class="uploaderdescription">
								<%=@photo.description unless @photo.description.blank? %>
							</div>

						</div>
					</div>
				</div>
			</div>

app/views/shared/_footer.html.erb
<footer>
	<div class="ui divided horizontal link list">
		<div class="item">Copyright © 2014 Jyootai</div>
	</div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container">
	<div class="container-fluid">
	  <div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		<a class="navbar-brand" href="/">Picshare</a>
	</div>
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li><%= link_to "上传", new_photo_path,"data-no-turbolink"=>true%></li>
			<li><%= link_to "所有照片", photos_path%></li>
			<li class="dropdown">
			  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="#">Action</a></li>
					<li><a href="#">Another action</a></li>
					<li><a href="#">Something else here</a></li>
					<li class="divider"></li>
					<li><a href="#">Separated link</a></li>
				  <li class="divider"></li>
					<li><a href="#">One more separated link</a></li>
		    </ul>
			</li>
  	</ul>
		<ul class="nav navbar-nav navbar-right">
			<%if user_signed_in?%>
				<li>
				  <%= link_to semantic_icon(:user)+ current_user.username, recent_users_path(current_user.username)%></li>
				<li>
					<div class="menu">
						<div class="ui simple dropdown item only icon">
							<i class="dropdown icon"></i>
							<div class="menu">
								<%=link_to semantic_icon(:photo)+"我的照片",user_home_path(current_user.username), :class=>"item"%>
								<%=link_to semantic_icon(:setting)+"设置",edit_settings_path, :class=>"item"%>
								<%=link_to semantic_icon(:key)+"密码修改",password_users_path, :class=>"item"%>
							</div>
							
						</div>
					</div>
				</li>
					<li><%= link_to semantic_icon('sign out'), destroy_user_session_path,"data-placement"=>"bottom","data-content"=>"退出" ,:id=>"Logout"%></li>
			<% else %>
				<%if controller_name=='welcomes' && action_name=='index'%>
					<li><a href="#myModal" data-toggle="modal">登录</a></li>
				<%else%>
					<li><%= link_to "登录",new_user_session_path%></li>
				<%end%>
			<%end%>

		</ul>
	</div>
	</div>
</nav>

app/views/users/edit.html.erb
<div id="user_edit" class="container">
	<div class="row">
		<div class="col-lg-3" >
			<%= render 'users/shared/vertical_menu'%>
		</div>
		<div class="col-lg-8 ">
			<div class="ui form segment">
				<%= form_for(current_user,:url=>settings_edit_path,:html=>{:multipart=>true,:method=>:patch}) do |f|%>	
				<div class=" ui header">基本资料</div>
				<p>修改你的基本帐号</p>
				<div class="head_area field">
					<%= image_tag current_user.avatar.smaller.url , :class=>"upload_head" %>
					<%= f.file_field :avatar, :class => "avatar"%>
				<br />	<p>你可以上传新的头像从你的电脑上</p>
				</div>
				<div class="field">
					<label>用户名</label>
					<%= f.text_field :username%>
				</div>
				<div class="field">
					<label>电子邮箱</label>
					<%= f.email_field :email%>
				</div>
			<div class="ui section divider "></div>
			<button type="submit" class="ui button green" tabindex="5">提交修改</button>
			<%end%>
			</div>
		</div>
	</div>
	
</div>

app/views/users/email.html.erb
<div id="user_edit" class="container">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'users/shared/vertical_menu'%>
		</div>
		<div class="col-lg-8">
				<div class="ui form segment">
				<%= form_for(current_user,:url=>edit_settings_path,:html=>{:method=>:patch}) do |f|%>	
					<div class=" ui header">邮件通知</div>
					<p>控制Picshare向你发送邮件的时间和频率</p>
					<div class="field">
						<label>电子邮箱</label>
						<%= f.email_field :email%>
					</div>
				<%end%>
				</div>
		</div>
		
	</div>
	
</div>

app/views/users/password.html.erb
<div id="user_edit" class="container">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'users/shared/vertical_menu'%>	
		</div>
		<div class="col-lg-8">
			<div class="ui form segment">
			<%= form_for(current_user,:url=>password_users_path,:html=>{:method=>:patch}) do |f|%>	
				<div class="ui header">密码</div>
				<p>更改你的密码或找回当前密码</p>
				<div class="field">
					<label>旧密码</label>
					<%= f.password_field :old_password,:required=>true%>
				</div>
				<div class="field">
					<label>新密码</label>
					<%= f.password_field :password%>
				</div>
			<div class="ui section divider "></div>
			<button  type="submit" class="ui button green">确认修改</button>
			<%end%>	
			</div>
			
		</div>
	</div>
</div>

app/views/users/profile.html.erb
<div id="user_edit" class="container">
	<div class="row">
		<div class="col-lg-3">
			<%= render "users/shared/vertical_menu"%>
		</div>
		<div class="col-lg-8">
			<div class="ui form segment">
			<%= form_for(current_user,:url=>profile_users_path,:html=>{:method=>:patch}) do |f|%>	
				<div class="ui header">个人资料</div>
				<p>改资料将出现在你的公开个人资料，搜索结果等地方</p>
				<div class="field">
					<label>姓名</label>
					<%= f.text_field :name%>
				</div>
				<div class="field">
					<label>城市</label>
					<%= f.text_field :city%>
				</div>
				<div class="field">
					<label>性别</label>
					<div class="ui selection dropdown">
						<%= f.hidden_field :sex %>
						<div class="default text">性别</div>
							<i class="dropdown icon"></i>
						<div class="menu ui transition hidden">
							<div class="item" data-value="male"><i class="male icon"></i>男性</div>
							<div class="item" data-value="female"><i class="female icon"></i>女性</div>
						</div>
					</div>
				</div>
				<div class="field">
					<label>个人主页</label>
					<%= f.text_field :website%>
				</div>
				<label>个人简介</label>
				<%= f.text_area :title,:as=>:textarea%>
			<div class="ui section divider "></div>
			<button  type="submit" class="ui button green">保存资料</button>
		  <%end%>
			</div>
		</div>
	</div>
</div>

app/views/users/recent.html.erb
<%= render "users/shared/info_display"%>
<div  id="user_photos" class="container">
	<div class="row">
		<%= render 'photos/shared/photo_display'%>	
	</div>
	
</div>

app/views/users/shared/_info_display.html.erb
<%content_for :head do%>
	<style type="text/css">
		body{
			background-image:url(<%= asset_path "photo_background.png"%>);
		}
		
	</style>
<%end%>
<div class="show_photo container">
	<div class="row">
		<div class="col-md-6">
			<div class="info_display">
				<%= link_to image_tag(@user.avatar.small.url), edit_settings_path,:class=>"avatar"%>
				<h2>
					<%= link_to @user.username, user_home_path(@user.username) %>
					<% if user_signed_in? %>
						<%= link_to edit_settings_path, :class => "ui basic button mini" do %>
							<i class="pencil icon"></i>编辑个人资料
						<% end %>
					<%end%>
				</h2>
				<ul class="detail">
					<% unless @user.title.blank?%>
					<li>
					<a class ="brief">
							<i class="info letter icon"></i><%= @user.title %>
					</a>
					</li>
					<%end %>
				</ul>
				<p><%=@user.created_at.strftime("%Y年%m月%d日") %>加入  当前共上传了 <strong><%= @user.photos.count%></strong> 照片</p>
			</div>
		</div>
		<div class="col-md-6">
			<div class="social_data">
				<ul class="detail">
					<% unless @user.city.blank?%>
					<li>
					<%= link_to  :class => "locality",:title=>"城市" do %>
							<i class="map marker icon"></i><%= @user.city %>
						<% end %>
					</li>
					<%end %>
					<% unless @user.email.blank?%>
					<li>
					<%= link_to "#", :class => "email",:title=>"电子邮件" do %>
							<i class="mail icon"></i><%= @user.email %>
						<% end %>
					</li>
					<%end %>
					<% unless @user.bio.blank?%>
					<li>
					<%= link_to "http://weibo.com/#{@user.bio}", :class => "weibo" ,:target=>"_blank",:title=>"微博"  do %>
							<i class="weibo icon"></i><%= @user.bio %>
						<% end %>
					</li>
					<%end %>
					<% unless @user.twitter.blank?%>
					<li>
					<%= link_to "https://twitter.com/#{@user.twitter}", :class => "twitter" ,:title=>"Twitter" do %>
							<i class="twitter icon"></i><%= @user.twitter %>
						<% end %>
					</li>
					<%end %>
					<% unless @user.facebook.blank?%>
					<li>
					<%= link_to "https://facebook.com/#{@user.facebook}", :class => "facebook" ,:title=>"Facebook" do %>
							<i class="facebook icon"></i><%= @user.facebook %>
						<% end %>
					</li>
					<%end %>
					<% unless @user.weixin.blank?%>
					<li>
					<%= link_to "#", :class => "weixin" ,:title=>"微信" do %>
							<i class="weixin icon"></i><%= @user.weixin %>
						<% end %>
					</li>
					<%end %>
				</ul>
			</div>	
		</div>
	</div>
	<div class="row">
		<div class="ui pointing menu">
      <%= link_to recent_users_path, :class=>"#{'active' if action_name == 'recent' } item" do%> 
				<i class="home icon"></i> 最近上传
			<%end%>
      <%= link_to user_home_path, :class=>"#{'active' if action_name == 'show' } item" do%> 
				<i class="photo icon"></i> 所有照片 
			<%end%>
		</div>
	</div>
</div>

app/views/users/shared/_vertical_menu.html.erb
<div class="ui vertical pointing menu ">
	<a class="item" href="/settings/edit">
		<%= image_tag(current_user.avatar.small.url)%>
	</a>
	<%= link_to  edit_settings_path,:class=>"#{'active' if action_name=='edit'} item" do %>
		<i class="home icon"></i> 帐号
	<%end%>
	<%= link_to  password_users_path,:class=>"#{'active' if action_name=='password'} item" do %>
		<i class="key icon"></i>密码修改
	<%end%>
	<%= link_to  email_settings_path,:class=>"#{'active' if action_name=='email'} item" do %>
		<i class="mail icon"></i> 邮件通知
	<%end%>
	<%= link_to  profile_users_path,:class=>"#{'active' if action_name=='profile'} item" do %>
		<i class="info icon"></i> 个人资料
	<%end%>
	<%= link_to  user_home_path(current_user.username),:class=>"item" do %>
		<i class="photo icon"></i> 我的相册
	<%end%>
	<%= link_to  social_users_path,:class=>"#{'active' if action_name=='social'} item" do %>
		<i class="users icon"></i> 社交资料
	<%end%>
</div>

app/views/users/show.html.erb
<%= render "users/shared/info_display"%>
<div  id="user_photos" class="container">
	<div class="row">
		<%= render 'photos/shared/photo_display'%>	
	</div>
</div>

app/views/users/social.html.erb
<div id="user_edit" class="container">
	<div class="row">
		<div class="col-lg-3" >
			<%= render 'users/shared/vertical_menu'%>
		</div>
		<div class="col-lg-8 ">
			<div class="ui form segment">
			<%= form_for(current_user,:url=>social_users_path,:html=>{:method=>:patch}) do |f|%>	
				<div class="ui header">社交资料</div>
				<p>添加或更改你的其它联系方式</p>
				<div class="field">
					<label>微博</label>
					<%= f.text_field :bio%>
				</div>
				<div class="field">
					<label>QQ</label>
					<%= f.text_field :qq%>
				</div>
				<div class="field">
					<label>微信</label>
					<%= f.text_field :weixin%>
				</div>
				<div class="field">
					<label>Twitter</label>
					<%= f.text_field :twitter%>
				</div>
				<div class="field">
					<label>Facebook</label>
					<%= f.text_field :facebook%>
				</div>
				<div class="field">
					<label>Github用户名</label>
					<%= f.text_field :github%>
				</div>
			<div class="ui section divider "></div>
			<button class="ui button green">提交修改</button>
			<%end%>
			</div>
		</div>
	</div>
	
</div>

app/views/welcomes/index.html.erb
<% content_for :head do  %>
	<style type="text/css">
		body{
			background-image: url(<%= asset_path "root.jpg"%>);
		}
		
	</style>
<%end%>

<div class="root_photo">
  <div id="main" class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-push-2"> 
  	<% if user_signed_in? %>
		<%else%>
				<h1  class="blog-title">
					Share your photos
				</h1>
				<h2 class="blog-desc">
					Picshare is a simple,powerful sharing platform that allows you to share your photos with everyone.
			  </h2>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-push-2">
			  <div class="ui form segment">
        	<%= form_for resource, :wrapper => :semantic_ui_no_label,as: resource_info,url: registration_path(resource_info),  :html => {:class => "root_registration"} do |f| %>
			   	<div class="inline fields">
				    <div class="field">
				    	<div class="ui left labeled icon input">
								<%= f.text_field :username, :required => true,:placeholder => "用户名",  "data-content" =>  "用户名: 允许字母, 数字和下划线 3～20个字符", :tabindex => 1 %>
	    					<i class="user icon"></i>
       			  </div>
						</div>
						<div class="field">
							<div class="ui left labeled icon input">
	    					<%= f.text_field :email, :required => true, :placeholder => "邮箱","data-content"=> "邮箱: 用来找回密码 / 接收通知", :tabindex => 2 %>
								<i class="mail icon"></i>
	  					</div>
						</div>
						<div class="field">
							<div class="ui left labeled icon input">
								<%= f.password_field :password, :required => true, :placeholder => "密码","data-content"=> "密码: 8个以上的字符", :tabindex => 3 %>
								<i class="lock icon"></i>
	  					</div>
						</div>
					<button type="submit" class="ui button green" tabindex="5">注 册</button>
					<% end%>
					<%end%>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button  class="close" type="submit" data-dismiss="modal" aria-hidden="true">× </button>
		
				<h2>登 录</h2>
			</div>
			<div class="modal-body">
				<div class="ui form segment">
				<%= form_for(resource, as: resource_info, url: session_path(resource_info)) do |f| %>
					<div class="field">
	  				<label >邮 箱</label>
						<div class="ui left labeled icon input">	
							<%= f.email_field :email,:placeholder=>"在这里输入邮箱", autofocus: true %>
							<i class="mail icon"></i>
						</div>
					</div>
					<div class="field">
			  		<label >密 码</label>
						<div class="ui left labeled icon input">
							<%= f.password_field :password, :placeholder=>"在这里输入你的密码",autocomplete: "off" %>
							<i class="lock icon"></i>
						</div>
					</div>
					<% if devise_mapping.rememberable? -%>
						<div><%= f.check_box :remember_me %> <label>记住我</label></div>
					<% end -%>
					<button type="submit" class="ui button blue " >登录</button>
					<% end %>
				</div>
  <p>还不是Picshare的用户吗？<%= link_to "注册",root_path%>成为我们的成员！ <br />
		忘记密码了？没关系，点击<%= link_to "找回密码", new_password_path(resource_info) %>。
	</p>
			</div>
		</div>
	</div>
</div>